# Generated by Django 4.1.5 on 2023-01-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=200)),
                ('NAMA', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TTL', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=100)),
                ('alamat', models.TextField()),
                ('jurusan', models.TextField()),
                ('gmail', models.TextField()),
            ],
        ),
    ]
