# Generated by Django 4.1.5 on 2023-01-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_delete_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='tanggal_lahir',
            field=models.DateField(max_length=20),
        ),
    ]
