# Generated by Django 4.1.5 on 2023-01-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_alter_siswa_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='hobi',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
