# Generated by Django 4.1.5 on 2023-01-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_siswa_hobi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='hobi',
        ),
    ]
